name: dockwatch
version: "1.0.0"
config-version: 2

profile: dockwatch

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  dockwatch:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
